snapshot

diff --git a/wio/wio b/wio/wio
--- a/wio/wio
+++ b/wio/wio
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-: ${TOKEN:=default}
+TOKEN=`cat ${TOKEN_PATH}`
 
 # TARGET is the sensor being scraped
 : ${TARGET_BASE_URL:=wio-mock}
@@ -17,13 +17,18 @@
 : ${PROMETHEUS_PORT:=9091}
 
 # Get temp reading
-echo "Info: getting temp.."
-
+echo "Info: getting ${TARGET_SENSOR}.."
 URL="${TARGET_BASE_URL}:${TARGET_BASE_PORT}/${TARGET_BASE_PATH}/${TARGET_SENSOR}/${TARGET_SENSOR_PATH}?access_token=${TOKEN}"
-echo "Info: ${URL}"
 
-METRIC=$(curl --silent -k "${URL}" 2>&1 | jq -r ".${TARGET_READING_KEY}")
+# debug
+echo "Debug: URL value is ${URL}"
+
+# Get metric reading
+METRIC=$(curl -sSk "${URL}" 2>&1 | jq -r ".${TARGET_READING_KEY}")
+
+# Fail if metric not found
+[[ -z "$METRIC" ]] && { echo "Error: METRIC is empty" ; exit 1; }
 
 # push metric to prometheus sink
 echo "Info: pushing ${METRIC} to prometheus"
-echo "${TARGET_READING_KEY} ${METRIC}" | curl --silent --data-binary @- "${PROMETHEUS_HOST}:${PROMETHEUS_PORT}/metrics/job/${TARGET_METRIC_GROUP}"
+echo "${TARGET_READING_KEY} ${METRIC}" | curl -sS --data-binary @- "${PROMETHEUS_HOST}:${PROMETHEUS_PORT}/metrics/job/${TARGET_METRIC_GROUP}"
